critics/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',user_views.register,name="register"),
    path('profile/',user_views.profile,name="profile"),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name="login"),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name="logout"),
    path('', include('main_app.urls')),
    # path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),
    
   

    # CRUD Routes for TV shows
    path('tvshows/', views.ShowList.as_view(), name='tvshows_index'),
    path('tvshows/<int:pk>/', views.ShowDetail.as_view(), name='tvshows_detail'),
    path('tvshows/create/', views.ShowCreate.as_view(), name='tvshows_create'),
    path('tvshows/<int:pk>/update/', views.ShowUpdate.as_view(), name='tvshows_update'),
    path('tvshows/<int:pk>/delete/', views.ShowDelete.as_view(), name='tvshows_delete'),
    path('tvshows/<int:model_id>/<int:category_id>/add_review', views.add_review, name='add_review_tvshow'),


    # # CRUD Routes for novels
    path('novels/', views.NovelList.as_view(), name='novels_index'),
    path('novels/<int:pk>/', views.NovelDetail.as_view(), name='novels_detail'),
    path('novels/create/', views.NovelCreate.as_view(), name='novels_create'),
    path('novels/<int:pk>/update/',
         views.NovelUpdate.as_view(), name='novels_update'),
    path('novels/<int:pk>/delete/',
         views.NovelDelete.as_view(), name='novels_delete'),
    path('novels/<int:model_id>/<int:category_id>/add_review', views.add_review, name='add_review_novel'),

    # # CRUD Routes for games
    path('games/', views.GameList.as_view(), name='games_index'),
    path('games/<int:pk>/', views.GameDetail.as_view(), name='games_detail'),
    path('games/create/', views.GameCreate.as_view(), name='games_create'),
    path('games/<int:pk>/update/', views.GameUpdate.as_view(), name='games_update'),
    path('games/<int:pk>/delete/', views.GameDelete.as_view(), name='games_delete'),
    path('games/<int:model_id>/<int:category_id>/add_review', views.add_review, name='add_review_game'),
# /<int:category_id>
    # CRUD Routes for Stars
    path('stars/', views.StarList.as_view(), name='stars_index'),
    path('stars/<int:pk>/', views.StarDetail.as_view(), name='stars_detail'),
    path('stars/create/', views.StarCreate.as_view(), name='stars_create'),
    path('stars/<int:pk>/update/',views.StarUpdate.as_view(), name='stars_update'),
    path('stars/<int:pk>/delete/',views.StarDelete.as_view(), name='stars_delete'),
    path('stars/<int:model_id>/<int:category_id>/add_review', views.add_review, name='add_review_star'),

    # CRUD Routes for directors
    path('directors/', views.DirectorList.as_view(), name='directors_index'),
    path('directors/<int:pk>/', views.DirectorDetail.as_view(),name='directors_detail'),
    path('directors/create/', views.DirectorCreate.as_view(),name='directors_create'),
    path('directors/<int:pk>/update/',views.DirectorUpdate.as_view(), name='directors_update'),
    path('directors/<int:pk>/delete/',views.DirectorDelete.as_view(), name='directors_delete'),
    path('directors/<int:model_id>/<int:category_id>/add_review', views.add_review, name='add_review_director'),
         

    # # CRUD Routes for authors
    path('authors/', views.AuthorList.as_view(), name='authors_index'),
    path('authors/<int:pk>/', views.AuthorDetail.as_view(),name='authors_detail'),
    path('authors/create/', views.AuthorCreate.as_view(),name='authors_create'),
    path('authors/<int:pk>/update/',views.AuthorUpdate.as_view(), name='authors_update'),
    path('authors/<int:pk>/delete/',views.AuthorDelete.as_view(), name='authors_delete'),
    path('authors/<int:model_id>/<int:category_id>/add_review', views.add_review, name='add_review_author'),
        # Many to Many
    # Associate a director with a show
    path('shows/<int:show_id>/assoc_toy/<int:director_id>/', views.assoc_director, name="assoc_director"),

    # Unassociate a Director from a Show
    path('shows/<int:show_id>/unassoc_toy/<int:director_id>/', views.unassoc_director, name="unassoc_director"),

]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
from django.forms import ModelForm



# Create your models here.


GENDER = (
    ('M', 'Male'),
    ('F', 'Female'),
)

NATIONALITY = (
    ('BHD', 'Bahrain'),
    ('KSA', 'Saudi Arabia'),
    ('USA', 'United States of America'),
    ('UAE', 'United Arab Emirates'),
    ('BRZ', 'Brazil'),
    ('AUS', 'Australia'),
)

CATEGORY = (
    ('1', 'TV Show'),
    ('2', 'Novel'),
    ('3', 'Game'),
    ('4', 'Star'),
    ('5', 'Director'),
    ('6', 'Author'),

)

RATING = (
    ('1', 'Really Bad'),
    ('2', 'Bad'),
    ('3', 'Average'),
    ('4', 'Above Average'),
    ('5', 'Extraordinary'),

)

GENRE = (
    ('Fight', 'Fight'),
    ('Sports', 'Sports'),
    ('Action', 'Action'),
    ('Puzzle', 'Puzzle'),
    ('Horror', 'Horror'),
    ('Comedy', 'Comedy'),
    ('Advernture', 'Adventure'),
    ('Sci-Fiction', 'Sci-Fiction')
)

SHOW = (
    ('Movies', 'Movies'),
    ('Series', 'Series'),
    ('Anime', 'Anime')
)



# Stars model..................................................................................................


class Stars(models.Model):
    name = models.CharField(max_length=50)
    gender = models.CharField(
        max_length=50, choices=GENDER, default=GENDER[0][0])
    nationality = models.CharField(
        max_length=50, choices=NATIONALITY, default=NATIONALITY[0][0])
    dob = models.DateField()
    movies = models.CharField(max_length=100)
    image = models.ImageField(upload_to='main_app/static/uploads/', default="")
    user = models.ForeignKey(User, on_delete=models.CASCADE)



    # Overridding
    def __str__(self):
        return self.name

    # Overridding
    def get_absolute_url(self):
        return reverse('stars_detail', kwargs={'pk': self.id})



# Director model...............................................................................
class Director(models.Model):
    name = models.CharField(max_length=100)
    gender = models.CharField(
        max_length=100, choices=GENDER, default=GENDER[0][0])
    nationality = models.CharField(
        max_length=25, choices=NATIONALITY, default=NATIONALITY[0][0])
    dob = models.DateField()
    image = models.ImageField(upload_to='main_app/static/uploads/', default="")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('directors_detail', kwargs={'pk': self.id})


# Author model...............................................................................
class Author(models.Model):
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=100, choices=GENDER, default=GENDER[0][0])
    nationality = models.CharField(max_length=25, choices=NATIONALITY, default=NATIONALITY[0][0])
    dob = models.DateField()
    image = models.ImageField(upload_to='main_app/static/uploads/', default="")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('authors_detail', kwargs={'pk': self.id})

        
# Novel model...............................................................................
class Novel(models.Model):
    title = models.CharField(max_length=150)
    sub_title = models.CharField(max_length=100)
    published_date = models.DateField()
    publisher = models.CharField(max_length=50)
    pages = models.IntegerField()
    image = models.ImageField(upload_to='main_app/static/uploads/', default="")
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('novels_detail', kwargs={'pk': self.id})


# Review model...............................................................................
class Review(models.Model):
    category_id = models.CharField(
        max_length=1, choices=CATEGORY, default=CATEGORY[0][0])
    reference_id = models.IntegerField()
    review = models.TextField()
    rating = models.CharField(
        max_length=1, choices=RATING, default=RATING[2][0])

    def __str__(self):
        return self.review
        
    # def reviews(self):
    #     return self.review_set.all()

    # def __str__(self):
    #     return f"{self.game.title} {self.get_review_display()}"
        # on {self.date}

    # class Meta:
    #     ordering = ['-date']

#  Game Model ........................................................
class Game(models.Model):

    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=200, default="")
    platform = models.CharField(max_length=200)
    genre = models.CharField(max_length=50, choices=GENRE, default=GENRE[0][0])
    release_date = models.DateField()
    image = models.ImageField(upload_to='main_app/static/uploads', default="")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    novel = models.ForeignKey(Novel, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('games_detail', kwargs={'pk': self.id})

# TV shows model..................................................................................................
class Tvshow(models.Model):
    type = models.CharField(max_length=50, choices=SHOW, default=SHOW[0][0])
    title = models.CharField(max_length=50)
    duration = models.DurationField()
    genre = models.CharField(max_length=50, choices=GENRE, default=GENRE[0][0])
    releaseDate = models.DateField()
    image = models.ImageField(upload_to='main_app/static/uploads/', default="")
    stars = models.ManyToManyField(Stars)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    director = models.ForeignKey(Director, on_delete=models.CASCADE,blank=True, null=True)
    novel = models.ForeignKey(Novel, on_delete=models.CASCADE,blank=True, null=True)
    game = models.OneToOneField(Game, on_delete=models.CASCADE)
    # Overridding
    def get_absolute_url(self):
        return reverse('tvshows_detail', kwargs={'pk': self.id})

    def __str__(self):
        return self.title

main_app/forms.py
from django.forms import ModelForm
from .models import Review
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['review', 'rating']


# class ProfileCreateForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ('first_name', 'last_name', 'gender', 'contact_number','dob' , 'image' , 'favorite_tv_show', 'favorite_novel', 'favorite_game')
#         widgets = {
#             "first_name": forms.TextInput(attrs={'class':'form-control'}),
#             "last_name": forms.TextInput(attrs={'class':'form-control'}),
#             "gender": forms.Select(choices=GENDER,attrs={'class':'form-control'}),
#             "contact_number": forms.TextInput(attrs={'class':'form-control'}),
#             "dob": forms.DateInput(attrs={'class':'form-control'}),
#             "image": forms.FileInput(attrs={'class':'form-control', "id" : "image_field"}),
#             "favorite_tv_show": forms.TextInput(attrs={'class':'form-control'}),
#             "favorite_novel": forms.TextInput(attrs={'class':'form-control'}),
#             "favorite_game": forms.TextInput(attrs={'class':'form-control'}),
#         }


# class ProfileCreateForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ('first_name', 'last_name', 'gender', 'contact_number','dob' , 'image' , 'favorite_tv_show', 'favorite_novel', 'favorite_game')
#         widgets = {
#             "first_name": forms.TextInput(attrs={'class':'form-control'}),
#             "last_name": forms.TextInput(attrs={'class':'form-control'}),
#             "gender": forms.Select(choices=GENDER,attrs={'class':'form-control'}),
#             "contact_number": forms.TextInput(attrs={'class':'form-control'}),
#             "dob": forms.DateInput(attrs={'class':'form-control'}),
#             "image": forms.FileInput(attrs={'class':'form-control', "id" : "image_field"}),
#             "favorite_tv_show": forms.TextInput(attrs={'class':'form-control'}),
#             "favorite_novel": forms.TextInput(attrs={'class':'form-control'}),
#             "favorite_game": forms.TextInput(attrs={'class':'form-control'}),
#         }

main_app/templates/main_app/author_detail.html
{% extends 'base.html' %} 
{% block content %}
<br>
<h1 id="mcenter">{{ author.title }}</h1>
<div class="row">
  <div class="col-md-3 offset-md-3"></div>
  <div class="col-md-3 offset-md-3"><button type="button" class="btn btn-secondary"><a style="color: white;" href="{% url 'authors_index' %}">go back to author list</a></button></div>
</div>
      <div class="container" data-aos="fade-up">
        <div class="row">
            <div id="flcon">
                <div>
                    <p>Name: {{ author.name }}</p>
                    <p>Gender: {{ author.get_gender_display }}</p>
                    <p>Nationality: {{ author.get_nationality_display }}</p>
                    <p>Date of Birth: {{ author.dob }}</p>
                </div>
                <div>

        {% load static %}
        <img
          width="auto"
          height="350px"
          src="{% static author.image|cut:'main_app/static/' %}"
        />
      </div>
    </div>
    
    <div class="card-action">
      <a class="btn btn-primary" href="{% url 'authors_update' author.id %}"
        >Edit</a
      >
      <a class="btn btn-primary" href="{% url 'authors_delete' author.id %}"
        >Delete</a
      >
    </div>
    <br />
    <hr />
    <br />
    <div>
      <h4>Have an opinion about this Author? Please review!</h4>
      <form action="{% url 'add_review_author' author.id '6' %}" method="post">
        {% csrf_token %} {{ review_form.as_p }}
        <input type="submit" value="Add Review" class="btn btn-primary" />
      </form>

      <br />

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Rating(out of 5)</th>
            <th>Reviews</th>
          </tr>
        </thead>

        <tbody>
          {% for review in all_reviews %} 
          {% if review.reference_id == author.id and review.category_id == "6" %}
          <tr>
            <td>{{ review.rating }}</td>
            <td>{{ review.review }}</td>
          </tr>
          {% endif %} {% endfor %}
          <div class="pagination">
            <span class="step-links">
              {% if all_reviews.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}

              <span class="current">
                Page {{ all_reviews.number }} of {{ all_reviews.paginator.num_pages }}.
              </span>

              {% if all_reviews.has_next %}
              <a href="?page={{ all_reviews.next_page_number }}">next</a>
              <a href="?page={{ all_reviews.paginator.num_pages }}"
                >last &raquo;</a
              >
              {% endif %}
            </span>
          </div>
        </tbody>
      </table>
    </div>

    <hr />

  </div>
</div>

{% endblock %}

main_app/templates/main_app/author_form.html
{% extends 'base.html' %} 

{% block content %}
<br>
{% if object %}
<div class="row">
    <div class="col-md-3 offset-md-3"><h1>Edit <span class="teal-text"> {{ object.title }}</span></h1></div><br>
    <div class="col-md-3 offset-md-3"><button type="button" class="btn btn-secondary"><a style="color: white;" href="{% url 'authors_index' %}">go back to author list</a></button></div>
  </div><br><br>


{% else %}
<h1 id="mcenter">Add Author</h1>
<div class="row">
    <div class="col-md-3 offset-md-3"></div>
    <div class="col-md-3 offset-md-3"><button type="button" class="btn btn-secondary"><a style="color: white;" href="{% url 'authors_index' %}">go back to author list</a></button></div>
  </div><br><br>
{% endif %}


<form action="" method="POST" enctype="multipart/form-data" id="cform">


  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <br>

  <input type="submit" value="Submit" class="btn btn-primary" />
</form>


{% endblock %}

main_app/templates/main_app/author_list.html
{% extends 'base.html' %} 

{% block content %}
{% load static %} 
<br><br>
<div class="row">
  <div class="col-md-3 offset-md-3"></div>
  <div class="col-md-3 offset-md-3"><button type="button" class="btn btn-secondary"><a style="color: white;" href="create/">add author</a></button></div>
</div>
<h1 id="mcenter">Authors</h1>


<section id="team" class="team section-bg">
<div class="container" data-aos="fade-up">
<div class="row">
{% for author in author_list reversed %}
<div
        class="col-lg-3 col-md-6 d-flex align-items-strech"
        data-aos="fade-up"
        data-aos-delay="300"
      >
        <div class="member">
          <a href="{% url 'authors_detail' author.id %}">
          <div class="member-img">
            <img id="gimg"
              src="{% static author.image|cut:'main_app/static/' %}"
              class="img-fluid"
              alt="" 
            />
          
          </div>
          
          <div class="member-info" id="ttll">
            <h4>{{ author.name }}</h4>
            <span>{{ author.get_gender_display }}</span>
            <span>{{ author.get_nationality_display }}</span>
          </div>
        </a>
        </div>
      </div>

      {% endfor %} 
      <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    </div>
</div>
</section>
{% endblock %}

main_app/templates/main_app/game_confirm_delete.html
{% extends 'base.html' %}


{% block content %}

<h1 id="mcenter"> Delete Game </h1>

<h4> Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn btn-primary px-5 py-2">
    <a href="{% url 'games_detail' object.id %}" class="btn btn-primary px-5 py-2">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/game_detail.html
{% extends 'base.html' %} 
{% block content %}


<div class="row">
  <div class="col-md-3 offset-md-3"></div>
  <div class="col-md-3 offset-md-3">
    <button type="button" class="btn btn-secondary">
      <a style="color: white" href="{% url 'games_index' %}"
        >go back to game list</a
      >
    </button>
  </div>
</div>
<h1 id="mcenter">{{ game.title }}</h1>
<div class="container" data-aos="fade-up">
  <div class="row">
    <div id="flcon">
      <div>
        <h4></h4>
        
        <p>Subtitle: {{ game.subtitle }}</p>
        <p>Platform: {{ game.platform }}</p>
        <p>Genre: {{ game.genre }}</p>
        <p>Release Date: {{ game.release_date }}</p>
      </div>
      <div>
        {% load static %}
        <img
          width="400px"
          height="200px"
          src="{% static game.image|cut:'main_app/static/' %}"
        />
      </div>
    </div>
    <div class="card-action">
      <a class="btn btn-primary" href="{% url 'games_update' game.id %}"
        >Edit</a
      >
      <a class="btn btn-primary" href="{% url 'games_delete' game.id %}"
        >Delete</a
      >
    </div>
    <br />
    <hr />
    <br />
    <div>
      <h4>Have an opinion about this game? Please review it!</h4>
      <form action="{% url 'add_review_game' game.id '3' %}" method="post">
        {% csrf_token %} {{ review_form.as_p }}
        <input type="submit" value="Add Review" class="btn btn-primary" />
      </form>

      <br />

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Rating(out of 5)</th>
            <th>Reviews</th>
          </tr>
        </thead>

        <tbody>
          {% for review in all_reviews %} {% if review.reference_id == game.id and review.category_id == "3" %}
          <tr>
            <td>{{ review.rating }}</td>
            <td>{{ review.review }}</td>
          </tr>
          {% endif %} {% endfor %}
          <div class="pagination">
            <span class="step-links">
              {% if all_reviews.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}

              <span class="current">
                Page {{ all_reviews.number }} of 
                {{ all_reviews.paginator.num_pages }}.
              </span>

              {% if all_reviews.has_next %}
              <a href="?page={{ all_reviews.next_page_number }}">next</a>
              <a href="?page={{ all_reviews.paginator.num_pages }}"
                >last &raquo;</a
              >
              {% endif %}
            </span>
          </div>
        </tbody>
      </table>
    </div>

    <hr />
  </div>
</div>

{% endblock %}

main_app/templates/main_app/game_form.html
{% extends 'base.html' %} 

{% block content %}

{% if object %}
<h1>Edit <span class="teal-text"> {{ object.name }}</span></h1>
{% else %}
<h1 id="mcenter">Add Game</h1>
{% endif %}


<form action="" method="POST" enctype="multipart/form-data" id="cform">


  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <br>

  <input type="submit" value="Submit" class="btn btn-primary" />
</form>


{% endblock %}

main_app/templates/main_app/novel_confirm_delete.html
{% extends 'base.html' %}


{% block content %}

<h1 id="mcenter"> Delete Novel </h1>

<h4> Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn btn-primary px-5 py-2">
    <a href="{% url 'novels_detail' object.id %}" class="btn btn-primary px-5 py-2">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/novel_detail.html
{% extends 'base.html' %} {% block content %}
<br />
<h1 id="mcenter">{{ novel.title }}</h1>
<div class="row">
  <div class="col-md-3 offset-md-3"></div>
  <div class="col-md-3 offset-md-3">
    <button type="button" class="btn btn-secondary">
      <a style="color: white" href="{% url 'novels_index' %}"
        >go back to novel list</a
      >
    </button>
  </div>
</div>
<div class="container" data-aos="fade-up">
  <div class="row">
    <div id="flcon">
      <div>
        <p>Subtitle: {{ novel.sub_title }}</p>
        <p>Published Date: {{ novel.published_date }}</p>
        <p>Publisher: {{ novel.publisher }}</p>
        <p>Pages : {{ novel.pages }}</p>
      </div>
      <div>
        {% load static %}
        <img
          width="auto"
          height="350px"
          src="{% static novel.image|cut:'main_app/static/' %}"
        />
      </div>
    </div>
    <div class="card-action">
      <a class="btn btn-primary" href="{% url 'novels_update' novel.id %}"
        >Edit</a
      >
      <a class="btn btn-primary" href="{% url 'novels_delete' novel.id %}"
        >Delete</a
      >
    </div>
    <br />
    <hr />
    <br />
    <div>
      <h4>Have an opinion about this Novel? Please review!</h4>
      <form action="{% url 'add_review_novel' novel.id '2' %}" method="post">
        {% csrf_token %} {{ review_form.as_p }}
        <input type="submit" value="Add Review" class="btn btn-primary" />
      </form>

      <br />

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Rating(out of 5)</th>
            <th>Reviews</th>
          </tr>
        </thead>

        <tbody>
          {% for review in all_reviews %} 
          {% if review.reference_id == novel.id and review.category_id == "2" %}
          <tr>
            <td>{{ review.rating }}</td>
            <td>{{ review.review }}</td>
          </tr>
          {% endif %} {% endfor %}
          <div class="pagination">
            <span class="step-links">
              {% if all_reviews.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}

              <span class="current">
                Page {{ all_reviews.number }} of {{all_reviews.paginator.num_pages }}.
              </span>

              {% if all_reviews.has_next %}
              <a href="?page={{ all_reviews.next_page_number }}">next</a>
              <a href="?page={{ all_reviews.paginator.num_pages }}"
                >last &raquo;</a
              >
              {% endif %}
            </span>
          </div>
        </tbody>
      </table>
    </div>

    <hr />
  </div>
</div>

{% endblock %}

main_app/templates/main_app/stars_list.html
{% extends 'base.html' %} 

{% block content %}
{% load static %} 
<div class="row">
  <div class="col-md-3 offset-md-3"></div>
  <div class="col-md-3 offset-md-3"><button type="button" class="btn btn-secondary"><a style="color: white;" href="create/">add Star</a></button></div>
</div>
<h1 style="text-align:center">Stars List</h1>

<section id="team" class="team section-bg">
<div class="container" data-aos="fade-up">
<div class="row">
{% for star in page_obj %}
<div
        class="col-lg-3 col-md-6 d-flex align-items-stretch"
        data-aos="fade-up"
        data-aos-delay="300"
      >
      <a href="{% url 'stars_detail' star.id %}" class="btn btn-primary" id="show_detail">
        <div class="member">
          <div class="member-img">
            <img src="{% static star.image|cut:'main_app/static/' %}" class="img-fluid" alt=""/>
          </div>
          
          <div class="member-info">
            <h4>{{ star.name }}</h4>
            <span> {{ star.get_nationality_display }}</span>
          </div>
          <div class="card-action">
          
          </div>
        </div></a>
      </div>

      {% endfor %}
      <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    </div>
</div>
</section>
<!-- <section>
  {% for star in page_obj  %}
    {# Each "contact" is a Contact model object. #}
    {{ star.name|upper }}<br>
    ...
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</section> -->
{% endblock %}